//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSForms2ES102_main.OkulIslemleri.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OkulDbEntities1 : DbContext
    {
        public OkulDbEntities1()
            : base("name=OkulDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBolumler> tblBolumler { get; set; }
        public virtual DbSet<tblOgrenciler> tblOgrenciler { get; set; }
        public virtual DbSet<tblSehirler> tblSehirler { get; set; }
    }
}
