//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSForms2ES102_main.OkulIslemleri.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBolumler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBolumler()
        {
            this.tblOgrenciler = new HashSet<tblOgrenciler>();
        }
    
        public int Id { get; set; }
        public string BolumAdi { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOgrenciler> tblOgrenciler { get; set; }
    }
}
