//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSForms2ES102_main.OkulIslemleri.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOgrenciler
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyadi { get; set; }
        public string OgrNo { get; set; }
        public string TcNo { get; set; }
        public Nullable<System.DateTime> Dtarihi { get; set; }
        public Nullable<int> BolumId { get; set; }
        public Nullable<int> SehirId { get; set; }
    
        public virtual tblBolumler tblBolumler { get; set; }
        public virtual tblSehirler tblSehirler { get; set; }
    }
}
